name: Ejecutar main.py

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11' 
          
      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Ejecutar main.py
        run: python main.py
