name: YAML Linter

on:
  push:
    paths:
      - '**/*.yaml'
      - '**/*.yml'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Instalar yamllint
        run: sudo apt-get install yamllint

      - name: Ejecutar yamllint
        run: |
          find . -name "*.yml" -o -name "*.yaml" | xargs yamllint
